# Generated by Django 4.2 on 2023-05-24 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plant', '0001_initial'),
        ('pot', '0002_alter_pot_plant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Senzors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('currentValue', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='pot',
            name='status',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pot',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='potsPlant', to='plant.plant'),
        ),
        migrations.AlterField(
            model_name='pot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potsUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SenzorValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('date', models.DateTimeField()),
                ('senzor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='senzors', to='pot.senzors')),
            ],
        ),
        migrations.AddField(
            model_name='pot',
            name='senzorBrightness',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='potsSenzorBrightness', to='pot.senzors'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pot',
            name='senzorHumidity',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='potsSenzorHumidity', to='pot.senzors'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pot',
            name='senzorPh',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='potsSenzorPh', to='pot.senzors'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pot',
            name='senzorTmp',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='potsSenzorTmp', to='pot.senzors'),
            preserve_default=False,
        ),
    ]
