# Generated by Django 4.2 on 2023-05-24 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pot', '0003_senzors_pot_status_alter_pot_plant_alter_pot_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='senzors',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='senzors',
            name='currentValue',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='senzorvalues',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
