# Generated by Django 4.2 on 2023-05-24 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
        ('pot', '0004_senzors_date_alter_senzors_currentvalue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pot',
            name='plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='potsPlant', to='plant.plant'),
        ),
    ]
