# Generated by Django 4.2 on 2023-05-24 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
        ('pot', '0005_alter_pot_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pot',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='potsPlant', to='plant.plant'),
        ),
    ]
