# Generated by Django 4.2 on 2023-05-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pot', '0006_alter_pot_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='pot',
            name='indoor',
            field=models.BooleanField(default=True),
        ),
    ]
