# Generated by Django 4.2.1 on 2023-05-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='plant_images')),
                ('humidity', models.CharField(max_length=255)),
                ('brightness', models.CharField(max_length=255)),
                ('temperature', models.CharField(max_length=255)),
                ('substrate', models.CharField(max_length=255)),
            ],
        ),
    ]
